### ISSUE TITLE
Update bootstrap-datepicker to latest version

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-framework#116]
It's good to have the ability to gray-out the disabled dates, unfortunately, our FW's version of `Datepicker` doesn't have `onRender` event, our copy of bootstrap-datepicker.js seems an old version.

See https://github.com/joomlatools/textman/pull/397/#issuecomment-323955720

**Comment by johanjanssens** [comment]
@ercanozkaya Can we upgrade the version?

**Comment by ercanozkaya** [comment]
We can update the datepicker but that requires a lot of testing and re-styling. The issue here is with the styling though.
@robinpoort Can you make sure .disabled gets a grayed out color in here?
https://github.com/timble/kodekit-ui/blob/4517315ef7df4b1b24e2570d0c2db139be6fc624/src/scss/admin/molecules/_datepicker.scss#L197-L197
You can test this on Docman document view publish on field. Past days have a `disabled` class but the same color.
