### ISSUE TITLE
 `composer update` produces a DB error related to extman tables. 

### ISSUE THREAD

**Issue by magneticmg** [joomlatools/joomlatools-framework#258]
Subsequent `composer update` produces a DB error related to extman tables. This happens after there has been a successful install and the $__extman_extensions table is already gone. 

#### Steps to reproduce the behavior

1. rm -rf vendor/ 
2. composer update

(Version 3.2.1)

**Comment by stevenrombauts** [comment]
Hi @magneticmg, we have been having similar issues as well and we are generally moving away from using Composer for extension installs in a continuous integration flow because of its complexity, both for deployments as for development work. Debugging has been a pain and different extensions seem to cause different problems. Simply put, there are too many moving parts that we do not control from inside the Composer plugin which makes this a difficult tool to work with in this context.

We're now testing the use of Git submodules for including our external extensions. This has some immediate benefits: code is part of the repository, we don't have to make any database or file changes anymore on deployment and we can easily work with other branches of our external extensions during development. We'll publish a blog post and add instructions to our [developer site](https://www.joomlatools.com/developer/) about this soon.

**Comment by stevenrombauts** [comment]
A little update, we've published a how-to for this new approach on our blog: https://www.joomlatools.com/blog/developer/continuous-deployment-with-git-submodules
