### ISSUE TITLE
Improve http format handling

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-framework#263]
Improve the format handling by moving it into the http package. This change allows the format methods to be used when outside of the context of the dispatcher, for example, when using a http request or response object directly.

**Comment by ercanozkaya** [comment]
@johanjanssens Reopening this. After these changes form submits now return a 204 instead of 303 due to resettable behavior not kicking in. 

* `\KDispatcherBehaviorResettable::isSupported` checks `\KHttpRequest::isFormSubmit` to kick in. 
* `\KHttpRequest::isFormSubmit` in turn calls `\KHttpRequest::getContentType`.
* Before the branch was merged content type would be returned as `application/x-www-form-urlencoded`. However after the merge it returns `text/html`

**Comment by jebbdomingo** [comment]
@johanjanssens @ercanozkaya is this good to go?

**Comment by ercanozkaya** [comment]
@jebbdomingo Good catch. This was merged already. Ticket was left open accidentally.
