### ISSUE TITLE
Problem when searching for keys on config objects

### ISSUE THREAD

**Issue by amazeika** [joomlatools/joomlatools-framework#54]
The array_search PHP function doesn't seem to properly work with assoc arrays. On my end I get wrong results when a key/value pair contains a true boolean value:

array_search('bad', array('first' => 'yeah', 'second' => 2, 'boolean' => true))

is returning "boolean".

**Comment by amazeika** [comment]
@ercanozkaya One for you to double check.

**Comment by ercanozkaya** [comment]
Moved the commit into a branch for discussion.

Right now KObjectConfig::remove supports two modes: 
* Remove by key 
* If key does not exist, remove by value

The original issue is that array_search is running in the non-strict mode, which means comparisons are made with ==. This will mean that whatever you search for, it will match true since `'bad' == true` in the original example. 

We can either solve this by adding the third strict parameter to array_search keeping the two operation modes in remove method.

Or we can use two methods remove and removeValue so we do not run into unexpected behavior.

Thoughts? @amazeika @johanjanssens

**Comment by amazeika** [comment]
@ercanozkaya As discussed in slack, I'm in favor or an additional method for searching for values. Adding the strict option to array_values might still return false results when searching by key, e.g.

array_search('three', array('one' => 'three', 'two' => 'four'), true)

will return 'one' when I'm looking for the 'three' key as in unset($config->three)

**Comment by johanjanssens** [comment]
Making a difference between values and keys negotiates the design of the config object, the idea is that that this is transparent. Therefor I would opted to solve this by enforcing strict values. 

@amazeika The problem you describe is a different issue and outside of the scope of the design of the Config object. Since this is not a problem you have right now, suggest to just table that and solve it by enforcing strict.

**Comment by amazeika** [comment]
I understand @johanjanssens but here transparency comes at a cost, the API is not rigorous. KObjectConfig is one important block of the FW and things like this may run into unexpected results.

Having said that I'm fine with adding the third parameter if you guys want to keep this functionality, this will solve my problem.

**Comment by johanjanssens** [comment]
@amazeika Agreed. My reply was in the context that this is a bug we want to solve. The change you suggest is more a feature, still happy to discuss that, since its not related to the issue at hand, suggest to solve that as suggested in the most simple way.

**Comment by amazeika** [comment]
@johanjanssens Sure, not a problem :) ... adding the third parameter will work for now, so let's just do that to avoid breaking functionality. The search by value is maybe being used somewhere.
